using System.ComponentModel;
using System.IO.Pipes;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using Microsoft.Win32.SafeHandles;

// The controller owns this pipe. EOF kills the job; a runner never inherits a controller handle.
static class Program {
 static readonly object Gate=new();
 static void Emit(object value){lock(Gate)Console.WriteLine(JsonSerializer.Serialize(value));}
 static int Main(string[] args){Console.InputEncoding=new UTF8Encoding(false,true);Console.OutputEncoding=new UTF8Encoding(false);try{if(args.Length==1&&args[0]=="doctor"){Emit(new{version=1,os="windows",suspended_spawn=true,kill_on_close=true});return 0;}if(args.Length==2&&args[0]=="job-status"){JobStatus(args[1]);return 0;}if(args.Length==2&&args[0]=="controller-lock"){ControllerLock(args[1]);return 0;}if(args.Length!=1||args[0]!="run")throw new Exception("Usage: DevFlow.WinHost run|doctor");Run().GetAwaiter().GetResult();return 0;}catch(Exception e){Emit(new{type="error",message=e.Message});return 1;}}
 static void ControllerLock(string key){if(!System.Text.RegularExpressions.Regex.IsMatch(key,@"^[a-f0-9]{64}$"))throw new Exception("Invalid controller key");using var mutex=new Mutex(false,@"Local\DevFlowController."+key);bool owned=false;try{try{owned=mutex.WaitOne(0);}catch(AbandonedMutexException){owned=true;}if(!owned)throw new Exception("Controller already active for this storage directory");Emit(new{locked=true});Console.ReadLine();}finally{if(owned)mutex.ReleaseMutex();}}
 static async Task Run(){var first=Console.ReadLine()??throw new Exception("Missing process specification");using var doc=JsonDocument.Parse(first);var s=doc.RootElement;var exe=s.GetProperty("executable").GetString()!;var cwd=s.GetProperty("cwd").GetString()!;if(!Path.IsPathFullyQualified(exe)||!File.Exists(exe)||!Directory.Exists(cwd))throw new Exception("Executable and cwd must be existing absolute paths");
 using var output=new AnonymousPipeServerStream(PipeDirection.In,HandleInheritability.Inheritable);using var error=new AnonymousPipeServerStream(PipeDirection.In,HandleInheritability.Inheritable);using var input=new AnonymousPipeServerStream(PipeDirection.Out,HandleInheritability.Inheritable);
 bool interactive=s.TryGetProperty("interactive",out var inter)&&inter.GetBoolean();
 var si=interactive?new STARTUPINFO{cb=Marshal.SizeOf<STARTUPINFO>()}:new STARTUPINFO{cb=Marshal.SizeOf<STARTUPINFO>(),dwFlags=0x100,hStdInput=input.ClientSafePipeHandle.DangerousGetHandle(),hStdOutput=output.ClientSafePipeHandle.DangerousGetHandle(),hStdError=error.ClientSafePipeHandle.DangerousGetHandle()};
 var env=new SortedDictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(var key in new[]{"SystemRoot","WINDIR","PATH","TEMP","TMP"})if(Environment.GetEnvironmentVariable(key) is string value)env[key]=value;foreach(var item in s.GetProperty("env").EnumerateObject()){if(item.Name.Contains('=')||item.Name.Contains('\0')||item.Value.GetString()!.Contains('\0'))throw new Exception("Invalid environment");env[item.Name]=item.Value.GetString()!;}var block=string.Join('\0',env.Select(p=>p.Key+"="+p.Value))+"\0\0";var envPtr=Marshal.StringToHGlobalUni(block);var command=new StringBuilder(Quote(exe)+" "+string.Join(" ",s.GetProperty("args").EnumerateArray().Select(a=>Quote(a.GetString()!))));
 using var job=new SafeFileHandle(CreateJobObject(IntPtr.Zero,JobName(s.GetProperty("id").GetString()!)),true);if(job.IsInvalid)Fail();if(Marshal.GetLastWin32Error()==183)throw new Exception("Job identifier already active");var limits=new JOBOBJECT_EXTENDED_LIMIT_INFORMATION();limits.BasicLimitInformation.LimitFlags=0x2000;var size=Marshal.SizeOf<JOBOBJECT_EXTENDED_LIMIT_INFORMATION>();var ptr=Marshal.AllocHGlobal(size);Marshal.StructureToPtr(limits,ptr,false);try{if(!SetInformationJobObject(job,9,ptr,(uint)size))Fail();}finally{Marshal.FreeHGlobal(ptr);}
 PROCESS_INFORMATION pi;try{if(s.TryGetProperty("identity",out _))throw new Exception("Alternate Windows identities are not supported");uint flags=0x4|0x400;if(!interactive)flags|=0x08000000;else flags|=0x00000010;if(!CreateProcess(exe,command,IntPtr.Zero,IntPtr.Zero,true,flags,envPtr,cwd,ref si,out pi))Fail();}finally{Marshal.FreeHGlobal(envPtr);}
 using var process=new SafeFileHandle(pi.hProcess,true);using var thread=new SafeFileHandle(pi.hThread,true);try{if(!AssignProcessToJobObject(job,process)){TerminateProcess(process,1);Fail();}output.DisposeLocalCopyOfClientHandle();error.DisposeLocalCopyOfClientHandle();input.DisposeLocalCopyOfClientHandle();if(ResumeThread(thread)==uint.MaxValue)Fail();Emit(new{type="started",pid=pi.dwProcessId,host_pid=Environment.ProcessId,id=s.GetProperty("id").GetString(),job_name=JobName(s.GetProperty("id").GetString()!)});
 _=Task.Run(()=>{try{while(true){var line=Console.ReadLine();if(line==null||JsonDocument.Parse(line).RootElement.GetProperty("action").GetString()=="stop"){TerminateJobObject(job,130);return;}}}catch{if(!job.IsClosed)TerminateJobObject(job,130);}});
 Task? stdout=null,stderr=null;if(!interactive){stdout=Pump(output,"stdout");stderr=Pump(error,"stderr");}if(s.TryGetProperty("stdin",out var stdin)){var bytes=Encoding.UTF8.GetBytes(stdin.GetString()!);await input.WriteAsync(bytes);}input.Dispose();
 await Task.Run(()=>WaitForSingleObject(process,0xffffffff));if(!GetExitCodeProcess(process,out var code))Fail();TerminateJobObject(job,code);if(stdout!=null&&stderr!=null)await Task.WhenAll(stdout,stderr);Emit(new{type="exit",code});
 }finally{if(!job.IsClosed)TerminateJobObject(job,130);}}
 static string JobName(string id){if(!System.Text.RegularExpressions.Regex.IsMatch(id,@"^[A-Za-z0-9_-]{1,150}$"))throw new Exception("Invalid job identifier");return @"Local\DevFlow."+id;}
 static void JobStatus(string id){using var job=new SafeFileHandle(OpenJobObject(4,false,JobName(id)),true);if(job.IsInvalid){if(Marshal.GetLastWin32Error()==2){Emit(new{id,alive=false,active_processes=0});return;}Fail();}var info=new JOBOBJECT_BASIC_ACCOUNTING_INFORMATION();if(!QueryInformationJobObject(job,1,ref info,(uint)Marshal.SizeOf<JOBOBJECT_BASIC_ACCOUNTING_INFORMATION>(),IntPtr.Zero))Fail();Emit(new{id,alive=info.ActiveProcesses>0,active_processes=info.ActiveProcesses});}
 [StructLayout(LayoutKind.Sequential)] struct JOBOBJECT_BASIC_ACCOUNTING_INFORMATION{public long TotalUserTime,TotalKernelTime,ThisPeriodTotalUserTime,ThisPeriodTotalKernelTime;public uint TotalPageFaultCount,TotalProcesses,ActiveProcesses,TotalTerminatedProcesses;}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr OpenJobObject(uint access,bool inherit,string name);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool QueryInformationJobObject(SafeFileHandle job,int cls,ref JOBOBJECT_BASIC_ACCOUNTING_INFORMATION value,uint length,IntPtr returned);
 static async Task Pump(Stream stream,string type){var bytes=new byte[8192];int n;while((n=await stream.ReadAsync(bytes))>0)Emit(new{type,data=Convert.ToBase64String(bytes,0,n)});}
 static string Quote(string value){if(value.Contains('\0'))throw new Exception("NUL argument");var b=new StringBuilder("\"");int slash=0;foreach(var c in value){if(c=='\\'){slash++;continue;}if(c=='\"'){b.Append('\\',slash*2+1);b.Append(c);}else{b.Append('\\',slash);b.Append(c);}slash=0;}b.Append('\\',slash*2);return b.Append('"').ToString();}
 static void Fail()=>throw new Win32Exception(Marshal.GetLastWin32Error());
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] struct STARTUPINFO{public int cb;public string? lpReserved,lpDesktop,lpTitle;public int dwX,dwY,dwXSize,dwYSize,dwXCountChars,dwYCountChars,dwFillAttribute,dwFlags;public short wShowWindow,cbReserved2;public IntPtr lpReserved2,hStdInput,hStdOutput,hStdError;}
 [StructLayout(LayoutKind.Sequential)] struct PROCESS_INFORMATION{public IntPtr hProcess,hThread;public uint dwProcessId,dwThreadId;}
 [StructLayout(LayoutKind.Sequential)] struct JOBOBJECT_BASIC_LIMIT_INFORMATION{public long PerProcessUserTimeLimit,PerJobUserTimeLimit;public uint LimitFlags;public UIntPtr MinimumWorkingSetSize,MaximumWorkingSetSize;public uint ActiveProcessLimit;public UIntPtr Affinity;public uint PriorityClass,SchedulingClass;}
 [StructLayout(LayoutKind.Sequential)] struct IO_COUNTERS{public ulong ReadOperationCount,WriteOperationCount,OtherOperationCount,ReadTransferCount,WriteTransferCount,OtherTransferCount;}
 [StructLayout(LayoutKind.Sequential)] struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION{public JOBOBJECT_BASIC_LIMIT_INFORMATION BasicLimitInformation;public IO_COUNTERS IoInfo;public UIntPtr ProcessMemoryLimit,JobMemoryLimit,PeakProcessMemoryUsed,PeakJobMemoryUsed;}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool CreateProcess(string app,StringBuilder cmd,IntPtr pa,IntPtr ta,bool inherit,uint flags,IntPtr env,string cwd,ref STARTUPINFO si,out PROCESS_INFORMATION pi);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr CreateJobObject(IntPtr attrs,string? name);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool SetInformationJobObject(SafeFileHandle job,int cls,IntPtr value,uint length);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool AssignProcessToJobObject(SafeFileHandle job,SafeFileHandle process);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool TerminateJobObject(SafeFileHandle job,uint code);
 [DllImport("kernel32.dll")]static extern bool TerminateProcess(SafeFileHandle process,uint code);
 [DllImport("kernel32.dll",SetLastError=true)]static extern uint ResumeThread(SafeFileHandle thread);
 [DllImport("kernel32.dll")]static extern uint WaitForSingleObject(SafeFileHandle handle,uint ms);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetExitCodeProcess(SafeFileHandle process,out uint code);
}
